[package]
name = "bdk_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = { version = "0.29.0", features = ["keys-bip39"] }
bitcoin = "0.30.1"
